
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dorpat

test:
  <<: *default
  database: dorpat_test

production:
  <<: *default
  database: dorpat-admin_production
  username: dorpat-admin
  password: <%= ENV['DORPAT-ADMIN_DATABASE_PASSWORD'] %>
